10:58:22.399 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:15)
11:03:08.888 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:15)
11:03:12.904 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:15)
11:05:41.290 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:15)
11:08:03.682 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
11:11:46.791 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
11:15:10.444 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
11:15:56.573 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
11:16:19.166 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
11:27:52.332 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
11:55:49.694 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost/order_mgmt
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
12:07:00.899 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.lang.ClassNotFoundException: com.mysql.jdvc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
12:07:16.227 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
12:07:45.488 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost/order_mgmt
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
12:24:51.396 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/order_mgmt
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
12:38:27.924 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost/order_mgmt
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:17)
12:40:46.505 [main] INFO  c.p.v.JdbcCustomerRepository -- customer name -> tester00
12:40:46.510 [main] INFO  c.p.v.JdbcCustomerRepository -- customer name -> tester01
12:40:46.510 [main] INFO  c.p.v.JdbcCustomerRepository -- customer name -> tester02
12:50:10.220 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 2077ebf3-fb35-3d8e-aabb-3b4e4530bb04, name -> tester00
12:50:10.227 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> a238abe4-1cbd-3efc-80c8-9fc257885339, name -> tester01
12:50:10.228 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> bc35f6ec-0d49-3289-8553-f6c6ee20982c, name -> tester02
12:57:34.395 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 2077ebf3-fb35-3d8e-aabb-3b4e4530bb04, name -> tester00
12:57:34.404 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> a238abe4-1cbd-3efc-80c8-9fc257885339, name -> tester01
12:57:34.405 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> bc35f6ec-0d49-3289-8553-f6c6ee20982c, name -> tester02
12:58:58.212 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 2077ebf3-fb35-3d8e-aabb-3b4e4530bb04, name -> tester00, createAt -> 2023-10-17T01:41:21
12:58:58.219 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> a238abe4-1cbd-3efc-80c8-9fc257885339, name -> tester01, createAt -> 2023-10-17T01:41:21
12:58:58.219 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> bc35f6ec-0d49-3289-8553-f6c6ee20982c, name -> tester02, createAt -> 2023-10-17T01:41:21
13:35:53.177 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0}' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.findNames(JdbcCustomerRepository.java:29)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:18)
13:37:38.759 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> a238abe4-1cbd-3efc-80c8-9fc257885339, name -> tester01, createAt -> 2023-10-17T01:41:21
13:37:38.774 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name: tester01
13:38:20.888 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 2077ebf3-fb35-3d8e-aabb-3b4e4530bb04, name -> tester00, createAt -> 2023-10-17T01:41:21
13:38:20.896 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> a238abe4-1cbd-3efc-80c8-9fc257885339, name -> tester01, createAt -> 2023-10-17T01:41:21
13:38:20.897 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> bc35f6ec-0d49-3289-8553-f6c6ee20982c, name -> tester02, createAt -> 2023-10-17T01:41:21
13:38:20.903 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name: tester00
13:38:20.903 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name: tester01
13:38:20.903 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name: tester02
13:45:20.865 [main] INFO  c.p.v.JdbcCustomerRepository -- statement -> com.mysql.cj.jdbc.ClientPreparedStatement: select * from customers WHERE name = 'tester01' OR 'a'='a'
18:06:09.345 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 2077ebf3-fb35-3d8e-aabb-3b4e4530bb04, name -> tester00, createAt -> 2023-10-17T01:41:21
18:06:09.350 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> a238abe4-1cbd-3efc-80c8-9fc257885339, name -> tester01, createAt -> 2023-10-17T01:41:21
18:06:09.350 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> bc35f6ec-0d49-3289-8553-f6c6ee20982c, name -> tester02, createAt -> 2023-10-17T01:41:21
18:06:09.350 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 90693e13-59b4-3219-be47-04840815883b, name -> new-user, createAt -> 2023-10-17T09:06:09
18:06:09.352 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name: tester00
18:06:09.352 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name: tester01
18:06:09.353 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name: tester02
18:06:09.353 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name: new-user
18:10:34.709 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 4
18:19:47.611 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 2
18:19:47.723 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.sql.SQLSyntaxErrorException: FUNCTION order_mgmt.UUID_ID_BIN does not exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.updateCustomerName(JdbcCustomerRepository.java:79)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:32)
18:19:47.761 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 3bb1e453-2f7f-3cb4-ae0a-f8bba114c0f4, name -> new-user, createAt -> 2023-10-17T09:19:47
18:19:47.761 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 1de968f0-2f5e-30a3-ab9e-66839ff1e4af, name -> new-user2, createAt -> 2023-10-17T09:19:47
18:19:47.763 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user
18:19:47.763 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user2
18:20:16.341 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 2
18:20:16.450 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.sql.SQLException: Incorrect string value: 'updateed-user2' for function uuid_to_bin
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.updateCustomerName(JdbcCustomerRepository.java:79)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:32)
18:20:16.482 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 97bfe814-594e-3431-9b75-dea75ba7f497, name -> new-user2, createAt -> 2023-10-17T09:20:16
18:20:16.482 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 784547ab-acfc-34c3-b40e-4b4e4dd1292f, name -> new-user, createAt -> 2023-10-17T09:20:16
18:20:16.484 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user2
18:20:16.484 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user
18:20:47.148 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 2
18:20:47.248 [main] ERROR c.p.v.JdbcCustomerRepository -- Got error while closing connection
java.sql.SQLException: Incorrect string value: 'updated-user2' for function uuid_to_bin
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.updateCustomerName(JdbcCustomerRepository.java:79)
	at com.prgrms.vouchermanager.JdbcCustomerRepository.main(JdbcCustomerRepository.java:32)
18:20:47.279 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> acffb623-0839-310d-96bd-c72e230421ee, name -> new-user2, createAt -> 2023-10-17T09:20:47
18:20:47.279 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> 03963c09-c15e-3733-85e4-1edcc152ed6a, name -> new-user, createAt -> 2023-10-17T09:20:47
18:20:47.281 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user2
18:20:47.281 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user
18:21:40.478 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 2
18:21:40.623 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> ffe65aa6-5afc-3aa8-804e-0e1f831f95e5, name -> new-user, createAt -> 2023-10-17T09:21:40
18:21:40.624 [main] INFO  c.p.v.JdbcCustomerRepository -- customer id -> d3f9f3ad-ba05-323d-b9fb-c277b0ac427c, name -> updated-user2, createAt -> 2023-10-17T09:21:40
18:21:40.625 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user
18:21:40.625 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : updated-user2
18:22:16.359 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 2
18:22:16.497 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user
18:22:16.497 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : updated-user2
18:24:19.362 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 2
18:24:19.499 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user
18:24:19.500 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user2
18:24:19.557 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : new-user
18:24:19.558 [main] INFO  c.p.v.JdbcCustomerRepository -- Found name : updated-user2
18:36:13.861 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 0
18:36:13.866 [main] INFO  c.p.v.JdbcCustomerRepository -- created customerId -> c34e7d42-aaaf-4b4c-a066-84081476e2e7
18:36:13.974 [main] INFO  c.p.v.JdbcCustomerRepository -- Found customerId : new-user
18:36:32.116 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 1
18:36:32.123 [main] INFO  c.p.v.JdbcCustomerRepository -- created customerId -> 1926fe14-4a2d-4453-b1ed-5a20e39fc91a
18:36:32.241 [main] INFO  c.p.v.JdbcCustomerRepository -- Found customerId : 1738bbd3-c006-3f7c-8f24-5300a5f0e938
18:43:54.801 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 1
18:43:54.809 [main] INFO  c.p.v.JdbcCustomerRepository -- created customerId -> d9b2f6d9-b4c6-4297-8f26-f0e1a2234484
18:43:54.936 [main] INFO  c.p.v.JdbcCustomerRepository -- Found customerId : d9b2f6d9-b4c6-4297-8f26-f0e1a2234484
22:55:05.780 [main] INFO  c.p.v.JdbcCustomerRepository -- deleted count -> 1
22:55:05.784 [main] INFO  c.p.v.JdbcCustomerRepository -- created customerId -> bb15bb41-1b07-4495-b23b-93fb45023bcb
22:55:05.850 [main] INFO  c.p.v.JdbcCustomerRepository -- Found customerId : bb15bb41-1b07-4495-b23b-93fb45023bcb
